### ISSUE TITLE
Path to JDK /usr/lib/sdk/openjdk10/jvm/openjdk-10.0.1 contains minor/micro (which may change?)

### ISSUE THREAD

**Issue by stbergmann** [flathub/org.freedesktop.Sdk.Extension.openjdk10#2]
<https://github.com/flathub/org.libreoffice.LibreOffice> currently bundles org.freedesktop.Sdk.Extensions.openjdk9, which has the JDK at /usr/lib/sdk/openjdk9/jvm/openjdk-9, i.e, at a path that (at least seemingly, in case later updates would have added minor/micro versions numbers to the path?) does not change with updates of that extension.  The LibreOffice Flatpak build system needs to specify that path as --with-jdk-home=/usr/lib/sdk/openjdk9/jvm/openjdk-9, see <https://cgit.freedesktop.org/libreoffice/core/tree/distro-configs/LibreOfficeFlatpak.conf?id=22effe2b8edf46539bde34497c6ac3201d70f5ed#n5>.

There is a request to update LibreOffice to bundle openjdk10 instead (<https://github.com/flathub/org.libreoffice.LibreOffice/issues/42>).  However, now the JDK is at /usr/lib/sdk/openjdk10/jvm/openjdk-10.0.1, so the LibreOffice Flatpak build system would presumably need to be adapted whenever the openjkd10 extension is updated.  (For tools like javac, there is symlinks from /usr/lib/sdk/bin to /usr/lib/sdk/openjdk10/jvm/openjdk-10.0.1, so to find such tools it would suffice for LibreOffice to use --with-jdk-home=/usr/lib/sdk/openjdk10.  However, that does not help the LibreOffice build to find e.g. jni.h.)

Is there a chance to make the JDK available at a fixed location?

**Comment by mbooth101** [comment]
Seems sensible; would a symlink be sufficient? For example, we could have:

/usr/lib/sdk/openjdk9/jvm/openjdk-9 -> /usr/lib/sdk/openjdk9/jvm/openjdk-9.0.4
/usr/lib/sdk/openjdk10/jvm/openjdk-10 -> /usr/lib/sdk/openjdk9/jvm/openjdk-10.0.1

**Comment by stbergmann** [comment]
would be fine for my needs

**Comment by mbooth101** [comment]
Please try the latest builds, they should contain the symlink I described above.

Fixed in 8690ee0
