### ISSUE TITLE
Smaller JRE

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.freedesktop.Sdk.Extension.openjdk10#3]
@mbooth101 Is it possible to get a smaller JRE? It's kind of massive currently at a couple of hundred MB. My uneducated memory is that it's possible to get a distributable JRE that's about 40mb or so, but it's possible that I'm just wrong.

**Comment by mbooth101** [comment]
Hmm, I've been looking into this and the short answer is "not really"

Do you have a use case in mind? It's possible you could create a JRE with limited APIs for headless applications, but I'm not sure how useful it would be.

**Comment by mbooth101** [comment]
FWIW, both the JREs 9 and 10 are about 171M in size. If you install the full JDK, it's about 480M.

**Comment by mbooth101** [comment]
Woo, I saw an easy win to bring the size of the JDK down. So now, when installing Java into your Flatpak application you can expect it to take up:

* JRE  ~171M
* JDK  ~239M

BTW, I looked at Oracle's JRE distribution and that weighs in at ~240M when installed on disk (Just the JRE, not even a JDK) so I don't think we are doing too badly on the size front.

**Comment by nedrichards** [comment]
Nice! Every little helps.

**Comment by mbooth101** [comment]
Okay well, I'll close this for now. We can always open a new bug if we have concrete ideas or goals in mind for a shrinkidunk JRE.

**Comment by mbooth101** [comment]
Just a further note to say that if you inspect a Java 11 application, you will find the installed size of the JRE is even smaller :-)

* 160M    /app/jre11/
* 220M    /app/jdk11/
