### ISSUE TITLE
Update/Upgrade to Freedesktop 18.08

### ISSUE THREAD

**Issue by x80486** [flathub/org.freedesktop.Sdk.Extension.openjdk10#5]
Is it possible to update this one, or create another `org.freedesktop.Sdk.Extension.openjdk10` that uses `Freedesktop 18.08`?

**Comment by TingPing** [comment]
We can make a `1.6` branch and turn master into `18.08` by doing something like this: https://github.com/flathub/buildbot-config/pull/38/files

**Comment by mbooth101** [comment]
For now, I am just rebuilding 18.08 and hopefully can forget about 1.6.

But thanks @TingPing I'll bare that in mind in case I need to go back :-)
